# Generated by Django 4.1.3 on 2022-11-29 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Уникальный URL')),
                ('title', models.CharField(max_length=100, verbose_name='Название приложения')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(default='default.png', upload_to='apps_images', verbose_name='Иконка приложения')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.groups', verbose_name='Группа приложения')),
            ],
            options={
                'verbose_name': 'Приложение',
                'verbose_name_plural': 'Приложения',
            },
        ),
    ]
