# Generated by Django 4.1.3 on 2022-11-30 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_comment_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='time',
        ),
    ]
