# Generated by Django 4.1.3 on 2022-12-01 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_remove_comment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='app',
            field=models.ForeignKey(default='app', on_delete=django.db.models.deletion.CASCADE, to='main.apps', verbose_name='Приложение'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='avtor',
            field=models.ForeignKey(default='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
